### ISSUE TITLE
Addon failed to load

### ISSUE THREAD

**Issue by p2501mk** [brownbat/autoEaseFactor#34]
Addon doesn't load.

Version 2.1.15 (442df9d6)
Qt 5.15.2 PyQt 5.15.2

When loading 'Auto Ease Factor':
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 80, in loadAddons
    __import__(dir)
  File "/home/p2501/.local/share/Anki2/addons21/1672712021/__init__.py", line 1, in <module>
    from . import autoEaseFactor
  File "/home/p2501/.local/share/Anki2/addons21/1672712021/autoEaseFactor.py", line 8, in <module>
    from aqt import gui_hooks
ImportError: cannot import name 'gui_hooks' from 'aqt' (/usr/share/anki/aqt/__init__.py)

Halp, dunno what to do..

**Comment by brownbat** [comment]
Ah, sorry, I should make a note explicitly on the add on page -- the earliest I've been able to test is around 2.1.21 (even then some features are limited).

Before .21 Anki works a lot differently with respect to hooks and add ons and some internal functions, so I'd have to rebuild a version from scratch specifically to work with it.

Thoughts on upgrading Anki? Are there other extensions holding you back on that version? 

(Not 100% sure, but it might be easier to patch those forward than to bring this one backward... might improve the performance of the program at the same time.)

**Comment by p2501mk** [comment]
I'm on Void Linux, so I've got runit instead of systemd. Also I have no wayland, so I'm pretty much tied to the Anki version in my native repository, sadly..
