### ISSUE TITLE
Error logged - How can it be fixed? [when reviews only is true]

### ISSUE THREAD

**Issue by Channah-Miryam** [brownbat/autoEaseFactor#35]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-27 08:30:26

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "aqt\reviewer.py", line 337, in _linkHandler
  File "aqt\reviewer.py", line 260, in _answerCard
  File "aqt\gui_hooks.py", line 2223, in __call__
  File "C:\Users\white\AppData\Roaming\Anki2\addons21\1672712021\autoEaseFactor.py", line 177, in adjust_factor
    display_stats(new_answer)
  File "C:\Users\white\AppData\Roaming\Anki2\addons21\1672712021\autoEaseFactor.py", line 162, in display_stats
    msg = get_stats(card, new_answer)
  File "C:\Users\white\AppData\Roaming\Anki2\addons21\1672712021\autoEaseFactor.py", line 145, in get_stats
    msg += f"MAvg factor: {round(average_ease, 2)}<br>"
TypeError: type NoneType doesn't define __round__ method

**Comment by Chana-Miryam** [comment]
I noticed that the review count in ANKI increases even when the cards are new and still in learning phase. Could this be the reason of the conflict?

**Comment by brownbat** [comment]
Sorry for the delay, having a hard time replicating this one. Can you tell me more about when this error occurs? 

Is it during reviews for every card, or just on new cards? Or when using the menu options? Or some other situation?

Is it happening all the time or only sometimes?

Thanks for the report!

**Comment by brownbat** [comment]
Reproduced and fixed. Please reopen if this reappears.
