### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by galantra** [brownbat/autoEaseFactor#51]
Today I've been getting the following error:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-21 19:09:56

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 991, in onStudyKey
  File "aqt\main.py", line 646, in moveToState
  File "aqt\main.py", line 668, in _reviewState
  File "aqt\reviewer.py", line 72, in show
  File "<decorator-gen-152>", line 2, in nextCard
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 80, in repl
  File "aqt\reviewer.py", line 125, in nextCard
  File "aqt\reviewer.py", line 215, in _showQuestion
  File "aqt\hooks_gen.py", line 2283, in __call__
  File "C:\Users\user\PortableApps\AnkiPortable\Anki2\addons21\1672712021\autoEaseFactor.py", line 29, in set_button_mode
    config = get_current_config(deck_id)
  File "C:\Users\user\PortableApps\AnkiPortable\Anki2\addons21\1672712021\autoEaseFactor.py", line 66, in get_current_config
    all_deck_settings = config["deck_settings"]
TypeError: 'NoneType' object is not subscriptable
```

It occurs in two occasions: 

- immediately after I click "Study Now"
- immediately after I click "Show Answer"

It occurs only _once_ in both occasions. It doesn't occurs when I repeat any of the two actions.

It is probably related to the newest update, because yesterday I didn't get this error.

Version ⁨2.1.40 (cf446733)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

Windows 10

**Comment by galantra** [comment]
Nevermind! I read in the ankiweb changelog that

> This caused an issue where the config became inaccessible, so reverting for now. Hopefully able to diagnose and push these options soon.

Then I "checked for updates". Indeed, there was already a new Auto Ease Factor update that I hadn't installed yet.

Now the error doesn't show up anymore.
